---
- hosts: all
  sudo: yes
  remote_user: root
  gather_facts: yes
  roles:
    - abtris.nginx-passenger
    - ushu.ruby-install
    - ushu.chruby
    - ANXS.postgresql
    - geerlingguy.redis
    - SimpliField.node
    - ocha.yarn
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
  tasks:
    - name: install prerequisites
      sudo: true
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - python-psycopg2
      tags:
        - packages
    - name: configure nginx
      become: true
      template:
        src: templates/nginx.conf
        dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    - name: Create postgresql user
      become: yes
      become_user: postgres
      postgresql_user: name=ideagrid
      notify: restart postgresql
    - name: Add the user 'ideagrid' and a primary group of 'admin'
      user:
        name: ideagrid
        comment: IdeaGrid deploy user
        group: admin
    - name: Set authorized key took from file
      authorized_key:
        user: ideagrid
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  vars:
    project_name: "{{ name }}"
    server_name: "{{ project_name }}.org"
