---
# tasks file for postgres
- name: install prerequisites for pg
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  tags:
    - packages
- name: Create postgresql user
  become: yes
  become_user: postgres
  postgresql_user: name=ideagrid
  notify: restart postgresql
