---
# tasks file for postgres
- name: install prerequisites for pg
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  tags:
    - packages

- name: Create postgresql user
  postgresql_user: name={{ ansible_ssh_user }} priv=ALL
