---
# tasks file for common
- name: 'install python2'
  raw: apt-get -y install python-simplejson
- name: Add the user 'ideagrid' and a primary group of 'admin'
  user:
    name: ideagrid
    comment: IdeaGrid deploy user
    group: admin
- name: Set authorized key took from file
  authorized_key:
    user: ideagrid
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
