---
# tasks file for ruby

- name: create chruby wrapper
  become: yes
  template:
    src: templates/chruby-wrapper.j2
    dest: /usr/local/bin/chruby-wrapper

- name: create chruby.sh
  become: yes
  template:
    src: templates/chruby.ch.j2
    dest: /etc/profile.d/chruby.sh

- name: install ruby 2.5.1
  raw: ruby-install ruby 2.5.1
